#-------------------------------
# General Site Settings
title: Pedro Torrealba Barra.
logo: '/images/logo.png'
description: Este es mi portafolio de artículos y notas de blogs que he escrito en los últimos años.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.pedrotorrealba.com" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# Author Settings
author:
  name: Pedro Torrealba Barra
  bio: Soy escritor y redactor de contenido en plataformas digitales. Aplico SEO a todo lo que escribo y me gusta usar emojis 🎩.
  avatar: '/images/02.png'

social:
- {icon: "ion-logo-linkedin", label: Linkedin, link: "https://www.linkedin.com/in/torrealba-p/"}
- {icon: "ion-logo-github", label: Github, link: "https://github.com/Robok3000"}
- {icon: "ion-logo-bitcoin", label: Bitcoin, link: "https://www.tiocripto.com/"}

# Example of adding a new link to the author section and footer - {icon: "ion-logo-github", label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Hero Settings
hero:
  hero__title: Hola, Soy Pedro! Redactor Creativo Digital
  hero__description: Me especializo en contenido para plataformas digitales. Aplico SEO a todo lo que escribo y me gusta usar emojis 🎩.
  hero__image: 'https://robok3000.github.io/lawebdelpiter/images/01.webp'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp: true # To enable the mailchimp form, use the value 'true'. To disable the form, use the value 'false' or leave the field blank.
mailchimp__title: Contáctame # Add your Title
mailchimp__text: Subscribe to our newsletter and we’ll send you the emails of latest posts. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: Join # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: torrealba.pedro@gmail.com # Add your email for contact form
  description: Te interesaría que escriba algo para ti? Entonces, conversemos y veamos cómo poner en palabras tus ideas. # Add a description of your form

# NOTE
# Joseph comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 100
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
